"""asf.cli — ``asf <command> [--product X]``.

Every record command resolves its record through :func:`resolve_record` (B-0050): the product's
``backlog_dir`` (``--product``, else ``$ASF_PRODUCT``, else ``default_product``), or the cwd only
when it *is* a record and no product resolves; the first line printed is ``record: <path>``. No
command creates anything under the cwd (``tests/test_path_resolution.py`` runs the whole table
from an empty directory). ``doctor`` and ``scheduler`` take the product, never the cwd.

The commands below are the week-1 fast-path set: today's record/tick/groom/rules tools, moved
behind product config. The fuller command surface (``init``, ``roadmap``, ``backlog``,
``product``, ``migrate-epic``, ...) lands with the 0.1 spec.
"""
import argparse
import os
import subprocess
import sys

from asf import __version__


def _git_sha(cwd=None):
    """The short sha the stamp names: ``cwd``'s repo (the product's ``repo_dir`` when the
    caller knows it — B-0050: from ``/tmp`` the shell's own repo said ``@unknown``)."""
    try:
        out = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], capture_output=True,
                             text=True, timeout=5, cwd=cwd or None)
        if out.returncode == 0:
            return out.stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        pass
    return 'unknown'


def stamp(command, repo=None):
    """The line every stamped table ends with: ``— generated by asf <command>@<sha> <HH:MM>``;
    the sha is ``repo``'s (the product's) when given, else the cwd's."""
    import datetime
    hhmm = datetime.datetime.now(datetime.timezone.utc).strftime('%H:%M')
    return f"— generated by asf {command}@{_git_sha(repo)} {hhmm}"


def build_parser():
    p = argparse.ArgumentParser(prog='asf', description='ASF — Autonomous Software Factory')
    p.add_argument('--version', action='version',
                   version=f'ASF — Autonomous Software Factory {__version__}')
    sub = p.add_subparsers(dest='command', required=True)

    p_new = sub.add_parser('new', help='mint a new work item')
    p_new.add_argument('type')
    p_new.add_argument('--title', required=True)
    p_new.add_argument('--parent')
    p_new.add_argument('--priority', choices=['need', 'nice'])
    p_new.add_argument('--area')
    p_new.add_argument('--legacy-id')
    p_new.add_argument('--body-file')
    p_new.add_argument('--force', action='store_true')
    p_new.add_argument('--product')
    from asf.record.new import add_arguments as add_new_bug_arguments
    add_new_bug_arguments(p_new)

    p_check = sub.add_parser('check', help='validate the backlog')
    p_check.add_argument('paths', nargs='*')
    p_check.add_argument('--product')

    p_index = sub.add_parser('index', help='rewrite Children/Backlinks and index.json')
    p_index.add_argument('--product')

    p_ingest = sub.add_parser('ingest', help='derive the machine block from product-repo evidence')
    p_ingest.add_argument('--fresh', action='store_true', help="bypass evidence's cache")
    p_ingest.add_argument('--product')

    p_migrate = sub.add_parser('migrate', help='create the live item set from the product repo')
    p_migrate.add_argument('--dry-run', action='store_true', help='print the table only')
    p_migrate.add_argument('--fresh', action='store_true', help="bypass evidence's cache")
    p_migrate.add_argument('--product')

    p_groom = sub.add_parser('groom', help='inbox -> cards, then write groom/<date>.md')
    p_groom.add_argument('--date', help='defaults to today (UTC)')
    p_groom.add_argument('--apply', action='store_true',
                         help="apply the previous groom file's answers first")
    p_groom.add_argument('--product')
    p_groom.add_argument('--default-bug-epic', help='the Epic an inbox Bug with no parent: line is filed under')

    p_stale = sub.add_parser('stale', help="items over their stage limit (the product's stage_limits)")
    p_stale.add_argument('--json', action='store_true')
    p_stale.add_argument('--product')

    p_file_bugs = sub.add_parser('file-bugs', help='file/bump Bugs from ci, refusals and rule violations')
    p_file_bugs.add_argument('--default-bug-epic', help='the Epic a filed Bug is parented under')
    p_file_bugs.add_argument('--product')

    p_rules = sub.add_parser('rules', help='run the rule checks')
    p_rules.add_argument('rules_command', choices=['check'])
    p_rules.add_argument('--product')
    p_rules.add_argument('--json', action='store_true')
    p_rules.add_argument('--verbose', action='store_true')

    p_evidence = sub.add_parser('evidence', help='the evidence pass (git/gh derived state)')
    p_evidence.add_argument('--product')
    p_evidence.add_argument('--fresh', action='store_true')

    p_harvest = sub.add_parser('harvest', help='land worker branches')
    p_harvest.add_argument('--repo')
    p_harvest.add_argument('--product')
    p_harvest.add_argument('--dry-run', action='store_true')

    p_pr_hygiene = sub.add_parser('pr-hygiene', help='sort open PRs into land/fix lanes')
    p_pr_hygiene.add_argument('--product')

    p_doctor = sub.add_parser('doctor', help='is this product\'s ASF install sound — one table')
    p_doctor.add_argument('--product')

    from asf.tick.tick import register as register_tick
    register_tick(sub)
    from asf.init import register_commands as register_install
    register_install(sub)
    from asf.scheduler import register as register_scheduler
    register_scheduler(sub)
    from asf.feeder.render import register as register_feeder
    register_feeder(sub)
    from asf.workers import register as register_workers
    register_workers(sub)
    from asf.briefs import register as register_briefs
    register_briefs(sub)
    from asf.metrics.import_sessions import register as register_import_sessions
    register_import_sessions(sub)
    from asf.approvals import register as register_approvals
    register_approvals(sub)
    from asf.redact import register as register_redact
    register_redact(sub)

    p_roadmap = sub.add_parser('roadmap', help='the ROADMAP table: one row per Epic')
    p_roadmap.add_argument('--product')

    p_backlog_view = sub.add_parser('backlog', help='the BOARD table: one row per Feature, grouped by Epic')
    p_backlog_view.add_argument('--product')

    p_parity = sub.add_parser('parity', help='the PARITY table: one row per Story')
    p_parity.add_argument('--product')

    p_prod = sub.add_parser('prod', help='the PROD table: deploy state and what just shipped')
    p_prod.add_argument('--product')

    p_sessions = sub.add_parser('sessions', help='the SESSIONS table')
    p_sessions.add_argument('--product')

    p_status = sub.add_parser('status', help='the FACTORY STATUS table')
    p_status.add_argument('--product')

    p_capacity = sub.add_parser('capacity', help='the CAPACITY table: sessions and CI runs per product')
    g_capacity = p_capacity.add_mutually_exclusive_group()
    g_capacity.add_argument('--product')
    g_capacity.add_argument('--all', action='store_true', help='every product under ~/.ASF/products/')
    p_capacity.add_argument('--json', action='store_true')

    from asf.tick.shadow_diff import build_parser as build_shadow_diff_parser
    p_shadow_diff = build_shadow_diff_parser(sub)
    p_shadow_diff.add_argument('--product')

    from asf import plugin_build
    plugin_build.register(sub)

    return p


def needs_operator_line(err, product=None):
    return f"NEEDS OPERATOR: {err} — edit the file or run asf init --product {product or '<p>'}"


ITEM_FOLDERS = ('epics', 'features', 'stories', 'tasks', 'bugs', 'decisions', 'rules')


def _looks_like_record(path):
    """``path`` is a record itself: it carries ``index.json`` or one of the item folders. A
    product repo's cwd (code, no item folders, no index) is never mistaken for one; neither is
    an empty directory."""
    return (os.path.isfile(os.path.join(path, 'index.json'))
            or any(os.path.isdir(os.path.join(path, d)) for d in ITEM_FOLDERS))


def resolve_record(args, announce=print):
    """The record a record command runs against. ``--product`` given explicitly always wins:
    that product's ``backlog_dir`` is the record, even when the cwd happens to be a record too —
    a product repo's cwd is never mistaken for one. Otherwise, a cwd that already looks like a
    record (an ``index.json`` beside ``epics/``) is used as it stands — the ordinary way these
    tools are run, from inside the backlog checkout. Only when the cwd is *not* a record (it is
    a product's code repo, say) does ``$ASF_PRODUCT`` or ``config.yaml``'s ``default_product``
    stand in, so the command still resolves the right record instead of silently doing nothing
    to the cwd. Prints ``record: <path>`` as the first line, so the operator always sees which
    one ran — through ``announce`` (stdout; ``new`` and ``stale`` send it to stderr, their stdout
    being a value a script reads: the minted id, the ``--json`` table)."""
    from asf import env
    name = getattr(args, 'product', None)
    cwd = os.getcwd()
    if name is None and _looks_like_record(cwd):
        announce(f"record: {cwd}")
        return cwd
    if name is None:
        name = env.default_product_name()
    record = env.load_product(name).backlog_dir
    if not record:
        raise env.ConfigError(f"product {name!r} has no backlog_dir configured")
    announce(f"record: {record}")
    return record


def _announce_stderr(line):
    print(line, file=sys.stderr)


def _product_of(argv):
    argv = list(sys.argv[1:] if argv is None else argv)
    for i, a in enumerate(argv):
        if a == '--product' and i + 1 < len(argv):
            return argv[i + 1]
        if a.startswith('--product='):
            return a.split('=', 1)[1]
    return None


def main(argv=None):
    from asf import env
    try:
        return _main(argv)
    except env.ConfigError as e:
        print(needs_operator_line(e, _product_of(argv)))
        return 2


def _main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    root = os.getcwd()  # only `hook` (a runtime hook in the project) and `plugin` run on the cwd

    if args.command == 'new':
        from asf.record.new import cmd_new
        return cmd_new(args, resolve_record(args, announce=_announce_stderr))
    if args.command == 'check':
        from asf.record.check import cmd_check
        return cmd_check(args, resolve_record(args))
    if args.command == 'index':
        from asf.record.index import cmd_index
        return cmd_index(args, resolve_record(args))
    if args.command == 'ingest':
        from asf.record.ingest import cmd_ingest
        return cmd_ingest(args, resolve_record(args))
    if args.command == 'migrate':
        from asf.tick.migrate import cmd_migrate
        return cmd_migrate(args, resolve_record(args))
    if args.command == 'groom':
        from asf.groom.groom import cmd_groom
        return cmd_groom(args, resolve_record(args))
    if args.command == 'stale':
        from asf.tick.stale import cmd_stale
        return cmd_stale(args, resolve_record(args, announce=_announce_stderr))  # stdout: the table / --json
    if args.command == 'file-bugs':
        from asf.tick.file_bugs import cmd_file_bugs
        return cmd_file_bugs(args, resolve_record(args))
    if args.command == 'rules':
        from asf.rules.rules import cmd_check as rules_cmd_check
        return rules_cmd_check(args, resolve_record(args))
    if args.command == 'evidence':
        from asf.evidence.evidence import main as evidence_main
        evidence_args = ['--json']
        if args.fresh:
            evidence_args.append('--fresh')
        if args.product:
            evidence_args += ['--product', args.product]
        return evidence_main(evidence_args)
    if args.command == 'harvest':
        from asf.harvest.harvest import main as harvest_main
        harvest_args = ['--repo', args.repo] if args.repo else []
        if args.dry_run:
            harvest_args.append('--dry-run')
        if args.product:
            harvest_args += ['--product', args.product]
        return harvest_main(harvest_args)
    if args.command == 'pr-hygiene':
        from asf.harvest.pr_hygiene import main as pr_hygiene_main
        pr_hygiene_args = ['--product', args.product] if args.product else []
        return pr_hygiene_main(pr_hygiene_args)
    if args.command == 'doctor':
        from asf.doctor import cmd_doctor
        return cmd_doctor(args, root)
    if args.command == 'tick':
        from asf.tick.tick import cmd_tick
        return cmd_tick(args)
    if args.command in ('roadmap', 'backlog', 'parity', 'prod', 'sessions', 'status'):
        view_root = resolve_record(args)
        if args.command == 'roadmap':
            from asf.views.roadmap import cmd_roadmap
            return cmd_roadmap(args, view_root)
        if args.command == 'backlog':
            from asf.views.board import cmd_backlog
            return cmd_backlog(args, view_root)
        if args.command == 'parity':
            from asf.views.parity import cmd_parity
            return cmd_parity(args, view_root)
        if args.command == 'prod':
            from asf.views.prod import cmd_prod
            return cmd_prod(args, view_root)
        if args.command == 'sessions':
            from asf.views.sessions import cmd_sessions
            return cmd_sessions(args, view_root)
        if args.command == 'status':
            from asf.views.status import cmd_status
            return cmd_status(args, view_root)
    if args.command == 'capacity':
        from asf.views.capacity import cmd_capacity
        return cmd_capacity(args)
    if args.command == 'shadow-diff':
        from asf.tick.shadow_diff import cmd_shadow_diff
        return cmd_shadow_diff(args)
    if args.command == 'scheduler':
        from asf.scheduler import cmd_scheduler
        return cmd_scheduler(args, root)
    # commands registered with set_defaults(run=…) (init, schema-migrate, upgrade, hooks, hook)
    if getattr(args, 'run', None):
        return args.run(args)
    # commands registered with set_defaults(func=…) (next, workers …)
    if getattr(args, 'func', None):
        return args.func(args)

    parser.print_help()
    return 2


if __name__ == '__main__':
    sys.exit(main())
