"""asf.cli — ``asf <command> [--product X]``.

The commands below are the week-1 fast-path set: today's record/tick/groom/rules tools, moved
behind product config. The fuller command surface (``init``, ``roadmap``, ``backlog``,
``product``, ``migrate-epic``, ...) lands with the 0.1 spec.
"""
import argparse
import os
import subprocess
import sys

from asf import __version__


def _git_sha():
    try:
        out = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], capture_output=True,
                             text=True, timeout=5)
        if out.returncode == 0:
            return out.stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        pass
    return 'unknown'


def stamp(command):
    """The line every stamped table ends with: ``— generated by asf <command>@<sha> <HH:MM>``."""
    import datetime
    hhmm = datetime.datetime.now(datetime.timezone.utc).strftime('%H:%M')
    return f"— generated by asf {command}@{_git_sha()} {hhmm}"


def build_parser():
    p = argparse.ArgumentParser(prog='asf', description='ASF — Autonomous Software Factory')
    p.add_argument('--version', action='version',
                   version=f'ASF — Autonomous Software Factory {__version__}')
    sub = p.add_subparsers(dest='command', required=True)

    p_new = sub.add_parser('new', help='mint a new work item')
    p_new.add_argument('type')
    p_new.add_argument('--title', required=True)
    p_new.add_argument('--parent')
    p_new.add_argument('--priority', choices=['need', 'nice'])
    p_new.add_argument('--area')
    p_new.add_argument('--legacy-id')
    p_new.add_argument('--body-file')
    p_new.add_argument('--force', action='store_true')

    p_check = sub.add_parser('check', help='validate the backlog')
    p_check.add_argument('paths', nargs='*')

    sub.add_parser('index', help='rewrite Children/Backlinks and index.json')

    p_ingest = sub.add_parser('ingest', help='derive the machine block from product-repo evidence')
    p_ingest.add_argument('--fresh', action='store_true', help="bypass evidence's cache")

    p_migrate = sub.add_parser('migrate', help='create the live item set from the product repo')
    p_migrate.add_argument('--dry-run', action='store_true', help='print the table only')
    p_migrate.add_argument('--fresh', action='store_true', help="bypass evidence's cache")
    p_migrate.add_argument('--product')

    p_groom = sub.add_parser('groom', help='inbox -> cards, then write groom/<date>.md')
    p_groom.add_argument('--date', help='defaults to today (UTC)')
    p_groom.add_argument('--apply', action='store_true',
                         help="apply the previous groom file's answers first")
    p_groom.add_argument('--product')
    p_groom.add_argument('--default-bug-epic', help='the Epic an inbox Bug with no parent: line is filed under')

    p_stale = sub.add_parser('stale', help='items over their tools/limits.json stage limit')
    p_stale.add_argument('--json', action='store_true')

    p_file_bugs = sub.add_parser('file-bugs', help='file/bump Bugs from ci, refusals and rule violations')
    p_file_bugs.add_argument('--default-bug-epic', help='the Epic a filed Bug is parented under')

    p_rules = sub.add_parser('rules', help='run the rule checks')
    p_rules.add_argument('rules_command', choices=['check'])
    p_rules.add_argument('--json', action='store_true')
    p_rules.add_argument('--verbose', action='store_true')

    p_evidence = sub.add_parser('evidence', help='the evidence pass (git/gh derived state)')
    p_evidence.add_argument('--product')
    p_evidence.add_argument('--fresh', action='store_true')

    p_harvest = sub.add_parser('harvest', help='land worker branches')
    p_harvest.add_argument('--repo')
    p_harvest.add_argument('--product')
    p_harvest.add_argument('--dry-run', action='store_true')

    p_pr_hygiene = sub.add_parser('pr-hygiene', help='sort open PRs into land/fix lanes')
    p_pr_hygiene.add_argument('--product')

    p_doctor = sub.add_parser('doctor', help='is this product\'s ASF install sound — one table')
    p_doctor.add_argument('--product')

    return p


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    root = os.getcwd()

    if args.command == 'new':
        from asf.record.new import cmd_new
        return cmd_new(args, root)
    if args.command == 'check':
        from asf.record.check import cmd_check
        return cmd_check(args, root)
    if args.command == 'index':
        from asf.record.index import cmd_index
        return cmd_index(args, root)
    if args.command == 'ingest':
        from asf.record.ingest import cmd_ingest
        return cmd_ingest(args, root)
    if args.command == 'migrate':
        from asf.tick.migrate import cmd_migrate
        return cmd_migrate(args, root)
    if args.command == 'groom':
        from asf.groom.groom import cmd_groom
        return cmd_groom(args, root)
    if args.command == 'stale':
        from asf.tick.stale import cmd_stale
        return cmd_stale(args, root)
    if args.command == 'file-bugs':
        from asf.tick.file_bugs import cmd_file_bugs
        return cmd_file_bugs(args, root)
    if args.command == 'rules':
        from asf.rules.rules import cmd_check as rules_cmd_check
        return rules_cmd_check(args, root)
    if args.command == 'evidence':
        from asf.evidence.evidence import main as evidence_main
        evidence_args = ['--json']
        if args.fresh:
            evidence_args.append('--fresh')
        if args.product:
            evidence_args += ['--product', args.product]
        return evidence_main(evidence_args)
    if args.command == 'harvest':
        from asf.harvest.harvest import main as harvest_main
        harvest_args = ['--repo', args.repo] if args.repo else []
        if args.dry_run:
            harvest_args.append('--dry-run')
        if args.product:
            harvest_args += ['--product', args.product]
        return harvest_main(harvest_args)
    if args.command == 'pr-hygiene':
        from asf.harvest.pr_hygiene import main as pr_hygiene_main
        pr_hygiene_args = ['--product', args.product] if args.product else []
        return pr_hygiene_main(pr_hygiene_args)
    if args.command == 'doctor':
        from asf.doctor import cmd_doctor
        return cmd_doctor(args, root)

    parser.print_help()
    return 2


if __name__ == '__main__':
    sys.exit(main())
