"""asf.cli — ``asf <command> [--product X]``.

Every record command resolves its record through :func:`resolve_record` (B-0050): the product's
``backlog_dir`` (``--product``, else ``$ASF_PRODUCT``, else ``default_product``), or the cwd only
when it *is* a record and no product resolves; the first line printed is ``record: <path>``. No
command creates anything under the cwd (``tests/test_path_resolution.py`` runs the whole table
from an empty directory). ``doctor`` and ``scheduler`` take the product, never the cwd.

The commands below are the week-1 fast-path set: today's record/tick/groom/rules tools, moved
behind product config. The fuller command surface (``init``, ``roadmap``, ``backlog``,
``product``, ``migrate-epic``, ...) lands with the 0.1 spec.
"""
import argparse
import os
import re
import subprocess
import sys

from asf import __version__


def _git_sha(cwd=None):
    """The short sha the stamp names: ``cwd``'s repo (the product's ``repo_dir`` when the
    caller knows it — B-0050: from ``/tmp`` the shell's own repo said ``@unknown``)."""
    try:
        out = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], capture_output=True,
                             text=True, timeout=5, cwd=cwd or None)
        if out.returncode == 0:
            return out.stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        pass
    return 'unknown'


#: The distribution name ``pyproject.toml`` installs the package under.
DIST_NAME = 'asf-factory'

#: A release tag, as ``metrics.next_tag`` cuts it: ``v<major>.<minor>.<patch>``.
RELEASE_TAG = re.compile(r'v\d+\.\d+\.\d+')


def _checkout_root():
    """The package's repo top level when it runs from a checkout, else ``None`` (the package's
    parent must be the repo's top level, so an enclosing repo never answers)."""
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    top = _checkout_git(root, 'rev-parse', '--show-toplevel')
    return root if top and os.path.realpath(top) == os.path.realpath(root) else None


def _checkout_git(root, *argv):
    """``git -C root <argv>``'s stripped stdout, or ``None`` when it fails or prints nothing."""
    try:
        out = subprocess.run(['git', '-C', root, *argv], capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.TimeoutExpired):
        return None
    return (out.stdout.strip() or None) if out.returncode == 0 else None


def _direct_url():
    """The install's PEP 610 ``direct_url.json`` as a dict (``{}`` when there is none)."""
    try:
        import importlib.metadata
        import json
        raw = importlib.metadata.distribution(DIST_NAME).read_text('direct_url.json')
        data = json.loads(raw or '{}')
        return data if isinstance(data, dict) else {}
    except Exception:  # noqa: BLE001 — no distribution, no file, bad JSON: nothing recorded
        return {}


def _release(root, direct_url):
    """The release this ``asf`` is: a git install's requested tag (``v0.1.1``), else a checkout's
    nearest release tag plus the commits past it (``v0.1.1+42``), else ``None``."""
    requested = (direct_url.get('vcs_info') or {}).get('requested_revision') or ''
    if isinstance(requested, str) and RELEASE_TAG.fullmatch(requested):
        return requested
    if root:
        described = _checkout_git(root, 'describe', '--tags', '--match', 'v[0-9]*') or ''
        m = re.fullmatch(r'(v\d+\.\d+\.\d+)(?:-(\d+)-g[0-9a-f]+)?', described)
        if m:
            return f'{m.group(1)}+{m.group(2)}' if m.group(2) not in (None, '0') else m.group(1)
    return None


def _source_commit(root, direct_url):
    """The short commit this ``asf`` was built from, or ``None``: a checkout's own HEAD, else a
    pipx git install's ``direct_url.json`` (``vcs_info.commit_id``)."""
    if root:
        head = _checkout_git(root, 'rev-parse', '--short', 'HEAD')
        if head:
            return head
    commit = (direct_url.get('vcs_info') or {}).get('commit_id')
    return commit[:7] if isinstance(commit, str) and commit else None


def version_string():
    """``v0.1.1 (47bab2d)`` — the release and, when known, the commit it was built from. The
    release is a git install's requested tag, else a checkout's nearest release tag with ``+N``
    commits past it, else the static ``__version__`` (never bumped: the tag is the version).
    ``asf --version`` and the doctor's stamp both print it."""
    root, direct_url = _checkout_root(), _direct_url()
    version = _release(root, direct_url) or __version__
    commit = _source_commit(root, direct_url)
    return f'{version} ({commit})' if commit else version


def stamp(command, repo=None, version=None):
    """The line every stamped table ends with: ``— generated by asf <command>@<sha> <HH:MM>``;
    the sha is ``repo``'s (the product's) when given, else the cwd's. ``version`` (asf's own
    :func:`version_string`) replaces the sha when a table reports on asf itself."""
    import datetime
    hhmm = datetime.datetime.now(datetime.timezone.utc).strftime('%H:%M')
    return f"— generated by asf {command}@{version or _git_sha(repo)} {hhmm}"


def build_parser():
    p = argparse.ArgumentParser(prog='asf', description='ASF — Autonomous Software Factory')
    p.add_argument('--version', action='version', version=f'asf {version_string()}')
    sub = p.add_subparsers(dest='command', required=True)

    p_new = sub.add_parser('new', help='mint a new work item')
    p_new.add_argument('type')
    p_new.add_argument('--title', required=True)
    p_new.add_argument('--parent')
    p_new.add_argument('--priority', choices=['need', 'nice'])
    p_new.add_argument('--area')
    p_new.add_argument('--legacy-id')
    p_new.add_argument('--body-file')
    p_new.add_argument('--force', action='store_true')
    p_new.add_argument('--product')
    from asf.record.new import add_arguments as add_new_shape_arguments
    add_new_shape_arguments(p_new)

    p_inbox = sub.add_parser(
        'inbox', help="file an untyped card into the record's intake dir (the groom types it)")
    p_inbox.add_argument('--title', required=True)
    p_inbox.add_argument('--body-file')
    p_inbox.add_argument('--parent')
    p_inbox.add_argument('--product')

    p_set = sub.add_parser('set', help='write typed fields of a card through the parser')
    p_set.add_argument('id')
    p_set.add_argument('assignments', nargs='+', metavar='FIELD=VALUE')
    p_set.add_argument('--product')

    p_check = sub.add_parser('check', help='validate the backlog')
    p_check.add_argument('paths', nargs='*')
    p_check.add_argument('--product')

    p_index = sub.add_parser('index', help='rewrite Children/Backlinks and index.json')
    p_index.add_argument('--product')

    p_ingest = sub.add_parser('ingest', help='derive the machine block from product-repo evidence')
    p_ingest.add_argument('--fresh', action='store_true', help="bypass evidence's cache")
    p_ingest.add_argument('--product')

    p_migrate = sub.add_parser('migrate', help='create the live item set from the product repo')
    p_migrate.add_argument('--dry-run', action='store_true', help='print the table only')
    p_migrate.add_argument('--fresh', action='store_true', help="bypass evidence's cache")
    p_migrate.add_argument('--product')

    p_idea = sub.add_parser('idea', help='an idea tree -> intake cards (the groom types them)')
    idea_sub = p_idea.add_subparsers(dest='idea_command', required=True)
    p_idea_apply = idea_sub.add_parser(
        'apply', help='file a tree the interrogator wrote as intake cards; no model call')
    p_idea_apply.add_argument('--tree', required=True, help='the tree file to apply')
    p_idea_apply.add_argument('--force', action='store_true',
                              help='apply a tree that was already applied')
    p_idea_apply.add_argument('--product')
    p_idea_apply.add_argument('--json', action='store_true', help='print the .applied JSON')

    p_groom = sub.add_parser('groom', help='inbox -> cards, then write groom/<date>.md')
    p_groom.add_argument('--date', help='defaults to today (UTC)')
    p_groom.add_argument('--apply', action='store_true',
                         help="apply the previous and today's groom file's answers first")
    p_groom.add_argument('--product')
    p_groom.add_argument('--default-bug-epic', help='the Epic an inbox Bug with no parent: line is filed under')

    p_stale = sub.add_parser('stale', help="items over their stage limit (the product's stage_limits)")
    p_stale.add_argument('--json', action='store_true')
    p_stale.add_argument('--product')

    p_file_bugs = sub.add_parser('file-bugs', help='file/bump Bugs from ci, refusals and rule violations')
    p_file_bugs.add_argument('--default-bug-epic', help='the Epic a filed Bug is parented under')
    p_file_bugs.add_argument('--product')

    p_rules = sub.add_parser('rules', help='run the rule checks')
    p_rules.add_argument('rules_command', choices=['check'])
    p_rules.add_argument('--product')
    p_rules.add_argument('--json', action='store_true')
    p_rules.add_argument('--verbose', action='store_true')

    p_evidence = sub.add_parser('evidence', help='the evidence pass (git/gh derived state)')
    p_evidence.add_argument('--product')
    p_evidence.add_argument('--fresh', action='store_true')

    p_harvest = sub.add_parser('harvest', help='land worker branches')
    p_harvest.add_argument('--repo')
    p_harvest.add_argument('--product')
    p_harvest.add_argument('--dry-run', action='store_true')

    p_pr_hygiene = sub.add_parser('pr-hygiene', help='sort open PRs into land/fix lanes')
    p_pr_hygiene.add_argument('--product')

    p_doctor = sub.add_parser('doctor', help='is this product\'s ASF install sound — one table')
    p_doctor.add_argument('--product')

    from asf.tick.tick import register as register_tick
    register_tick(sub)
    from asf.init import register_commands as register_install
    register_install(sub)
    from asf.scheduler import register as register_scheduler
    register_scheduler(sub)
    from asf.feeder.render import register as register_feeder
    register_feeder(sub)
    from asf.workers import register as register_workers
    register_workers(sub)
    from asf.workers.unpark import register as register_unpark
    register_unpark(sub)
    from asf.briefs import register as register_briefs
    register_briefs(sub)
    from asf.metrics.import_sessions import register as register_import_sessions
    register_import_sessions(sub)
    from asf.approvals import register as register_approvals
    register_approvals(sub)
    from asf.redact import register as register_redact
    register_redact(sub)

    p_roadmap = sub.add_parser('roadmap', help='the ROADMAP table: one row per Epic')
    p_roadmap.add_argument('--product')

    p_backlog_view = sub.add_parser('backlog', help='the BOARD table: one row per Feature, grouped by Epic')
    p_backlog_view.add_argument('--product')

    p_parity = sub.add_parser('parity', help='the PARITY table: one row per Story')
    p_parity.add_argument('--product')

    p_prod = sub.add_parser('prod', help='the PROD table: deploy state and what just shipped')
    p_prod.add_argument('--product')

    p_sessions = sub.add_parser('sessions', help='the SESSIONS table')
    p_sessions.add_argument('--product')

    p_tokens = sub.add_parser('tokens', help='the TOKENS table: input tokens per session, before and after a day')
    p_tokens.add_argument('--product')
    p_tokens.add_argument('--split', metavar='DAY', help='the day the change landed (default: today); counts as after')
    p_tokens.add_argument('--days', type=int, default=14, help='days each side of the split (default: 14)')
    p_tokens.add_argument('--json', action='store_true')

    p_status = sub.add_parser('status', help='the FACTORY STATUS table')
    p_status.add_argument('--product')

    p_capacity = sub.add_parser('capacity', help='the CAPACITY table: sessions and CI runs per product')
    g_capacity = p_capacity.add_mutually_exclusive_group()
    g_capacity.add_argument('--product')
    g_capacity.add_argument('--all', action='store_true', help='every product under ~/.ASF/products/')
    p_capacity.add_argument('--json', action='store_true')

    from asf.tick.shadow_diff import build_parser as build_shadow_diff_parser
    p_shadow_diff = build_shadow_diff_parser(sub)
    p_shadow_diff.add_argument('--product')

    from asf import plugin_build
    plugin_build.register(sub)

    return p


def needs_operator_line(err, product=None):
    return f"NEEDS OPERATOR: {err} — edit the file or run asf init --product {product or '<p>'}"


ITEM_FOLDERS = ('epics', 'features', 'stories', 'tasks', 'bugs', 'decisions', 'rules')


def _looks_like_record(path):
    """``path`` is a record itself: it carries ``index.json`` or one of the item folders. A
    product repo's cwd (code, no item folders, no index) is never mistaken for one; neither is
    an empty directory."""
    return (os.path.isfile(os.path.join(path, 'index.json'))
            or any(os.path.isdir(os.path.join(path, d)) for d in ITEM_FOLDERS))


def resolve_record(args, announce=print):
    """The record a record command runs against. ``--product`` given explicitly always wins:
    that product's ``backlog_dir`` is the record, even when the cwd happens to be a record too —
    a product repo's cwd is never mistaken for one. Otherwise, a cwd that already looks like a
    record (an ``index.json`` beside ``epics/``) is used as it stands — the ordinary way these
    tools are run, from inside the backlog checkout. Only when the cwd is *not* a record (it is
    a product's code repo, say) does ``$ASF_PRODUCT`` or ``config.yaml``'s ``default_product``
    stand in, so the command still resolves the right record instead of silently doing nothing
    to the cwd. Prints ``record: <path>`` as the first line, so the operator always sees which
    one ran — through ``announce`` (stdout; ``new`` and ``stale`` send it to stderr, their stdout
    being a value a script reads: the minted id, the ``--json`` table)."""
    from asf import env
    name = getattr(args, 'product', None)
    cwd = os.getcwd()
    if name is None and _looks_like_record(cwd):
        announce(f"record: {cwd}")
        return cwd
    if name is None:
        name = env.default_product_name()
    record = env.load_product(name).backlog_dir
    if not record:
        raise env.ConfigError(f"product {name!r} has no backlog_dir configured")
    announce(f"record: {record}")
    return record


def _announce_stderr(line):
    print(line, file=sys.stderr)


def _product_of(argv):
    argv = list(sys.argv[1:] if argv is None else argv)
    for i, a in enumerate(argv):
        if a == '--product' and i + 1 < len(argv):
            return argv[i + 1]
        if a.startswith('--product='):
            return a.split('=', 1)[1]
    return None


def line_buffered(*streams):
    """Flush each stream at every newline. A scheduled tick writes to a log file, where Python
    block-buffers: a tick running twenty minutes showed nothing of itself until it ended. A
    stream that cannot be reconfigured (a test's StringIO) is left alone."""
    for stream in streams:
        try:
            stream.reconfigure(line_buffering=True)
        except (AttributeError, ValueError, OSError):
            pass


def _utc_today():
    import datetime
    return datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d')


def _published(cmd, args, record, message):
    """Run a console command that writes the record, then commit and push what it wrote
    (:func:`asf.record.publish.publish_changes`): the tick's clone resets to origin, so an edit
    left in the operator's checkout never reaches it. The tick calls these commands on its own
    clone directly, never through here, so its state commit stays its own."""
    from asf.record import publish
    before = publish.snapshot(record)
    rc = cmd(args, record)
    publish.publish_changes(record, before, message)
    return rc


def main(argv=None):
    from asf import env, tables
    line_buffered(sys.stdout, sys.stderr)  # before BoxStream wraps stdout, which passes lines on
    finish = tables.install()   # markdown tables are drawn as box tables on a console
    try:
        return _main(argv)
    except env.ConfigError as e:
        print(needs_operator_line(e, _product_of(argv)))
        return 2
    finally:
        finish()


def _main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    root = os.getcwd()  # only `hook` (a runtime hook in the project) and `plugin` run on the cwd

    if args.command == 'new':
        from asf.record.new import cmd_new
        return cmd_new(args, resolve_record(args, announce=_announce_stderr))
    if args.command == 'inbox':
        from asf.groom.inbox import cmd_inbox
        return cmd_inbox(args, resolve_record(args, announce=_announce_stderr))
    if args.command == 'idea':
        from asf.idea.cli import cmd_idea
        return cmd_idea(args, resolve_record(args, announce=_announce_stderr))
    if args.command == 'set':
        from asf.record.setfield import cmd_set
        return _published(cmd_set, args, resolve_record(args, announce=_announce_stderr),
                          f"record: set {args.id}")
    if args.command == 'check':
        from asf.record.check import cmd_check
        return cmd_check(args, resolve_record(args))
    if args.command == 'index':
        from asf.record.index import cmd_index
        return cmd_index(args, resolve_record(args))
    if args.command == 'ingest':
        from asf.record.ingest import cmd_ingest
        return cmd_ingest(args, resolve_record(args))
    if args.command == 'migrate':
        from asf.tick.migrate import cmd_migrate
        return cmd_migrate(args, resolve_record(args))
    if args.command == 'groom':
        from asf.groom.groom import cmd_groom
        return _published(cmd_groom, args, resolve_record(args),
                          f"groom: {args.date or _utc_today()}" + (' --apply' if args.apply else ''))
    if args.command == 'stale':
        from asf.tick.stale import cmd_stale
        return cmd_stale(args, resolve_record(args, announce=_announce_stderr))  # stdout: the table / --json
    if args.command == 'file-bugs':
        from asf.tick.file_bugs import cmd_file_bugs
        return cmd_file_bugs(args, resolve_record(args))
    if args.command == 'rules':
        from asf.rules.rules import cmd_check as rules_cmd_check
        return rules_cmd_check(args, resolve_record(args))
    if args.command == 'evidence':
        from asf.evidence.evidence import main as evidence_main
        evidence_args = ['--json']
        if args.fresh:
            evidence_args.append('--fresh')
        if args.product:
            evidence_args += ['--product', args.product]
        return evidence_main(evidence_args)
    if args.command == 'harvest':
        from asf.harvest.harvest import main as harvest_main
        harvest_args = ['--repo', args.repo] if args.repo else []
        if args.dry_run:
            harvest_args.append('--dry-run')
        if args.product:
            harvest_args += ['--product', args.product]
        return harvest_main(harvest_args)
    if args.command == 'pr-hygiene':
        from asf.harvest.pr_hygiene import main as pr_hygiene_main
        pr_hygiene_args = ['--product', args.product] if args.product else []
        return pr_hygiene_main(pr_hygiene_args)
    if args.command == 'doctor':
        from asf.doctor import cmd_doctor
        return cmd_doctor(args, root)
    if args.command == 'tick':
        from asf.tick.tick import cmd_tick
        return cmd_tick(args)
    if args.command in ('roadmap', 'backlog', 'parity', 'prod', 'sessions', 'status', 'tokens'):
        view_root = resolve_record(args, announce=_announce_stderr if getattr(args, 'json', False) else print)
        if args.command == 'roadmap':
            from asf.views.roadmap import cmd_roadmap
            return cmd_roadmap(args, view_root)
        if args.command == 'backlog':
            from asf.views.board import cmd_backlog
            return cmd_backlog(args, view_root)
        if args.command == 'parity':
            from asf.views.parity import cmd_parity
            return cmd_parity(args, view_root)
        if args.command == 'prod':
            from asf.views.prod import cmd_prod
            return cmd_prod(args, view_root)
        if args.command == 'sessions':
            from asf.views.sessions import cmd_sessions
            return cmd_sessions(args, view_root)
        if args.command == 'tokens':
            from asf.views.tokens import cmd_tokens
            return cmd_tokens(args, view_root)
        if args.command == 'status':
            from asf.views.status import cmd_status
            return cmd_status(args, view_root)
    if args.command == 'capacity':
        from asf.views.capacity import cmd_capacity
        return cmd_capacity(args)
    if args.command == 'shadow-diff':
        from asf.tick.shadow_diff import cmd_shadow_diff
        return cmd_shadow_diff(args)
    if args.command == 'scheduler':
        from asf.scheduler import cmd_scheduler
        return cmd_scheduler(args, root)
    # commands registered with set_defaults(run=…) (init, schema-migrate, upgrade, hooks, hook)
    if getattr(args, 'run', None):
        return args.run(args)
    # commands registered with set_defaults(func=…) (next, workers …)
    if getattr(args, 'func', None):
        return args.func(args)

    parser.print_help()
    return 2


if __name__ == '__main__':
    sys.exit(main())
