"""asf.init — ``asf init --product <name> [--repo DIR] [--backlog DIR]``: the adopter.

1. The product config. ``~/.ASF/products/<name>.yaml`` is read if it exists; otherwise it is
   written from discovery over the product repo (``--repo``, default the cwd): the ``origin``
   slug, the default branch, the specs/plans dirs, the CI provider and the test command, with a
   ``# TODO`` on every key discovery could not fill. An existing file is never overwritten — init
   prints the diff it would have made instead.
2. The record. A backlog dir that is already ASF-shaped (the seven item folders plus
   ``index.json``) is adopted as-is: ``schema_version`` is stamped into ``index.json`` if absent
   and nothing is minted. Anything else gets the layout laid down: the item folders, the stream
   folders, the schema ``README.md``, a ``.githooks/pre-commit`` running ``asf check`` and an
   empty stamped ``index.json``.
3. ``asf index``, then the roadmap.
"""
import difflib
import glob
import json
import os
import re
import subprocess
import sys

from asf import env, schema
from asf.conventions import (DEFAULT_BRANCH_PREFIXES, DEFAULT_INTAKE_DIR, DEFAULT_PLANS_DIR,
                             DEFAULT_SPECS_DIR)

ITEM_FOLDERS = ('epics', 'features', 'stories', 'tasks', 'bugs', 'decisions', 'rules')
STREAM_FOLDERS = ('groom', 'releases', 'metrics/ci', 'metrics/sessions', 'metrics/ticks',
                  'metrics/events', 'metrics/daily')

PRE_COMMIT = """#!/bin/sh
# The record's pre-commit hook, written by `asf init`: a commit that fails `asf check` on the
# files it touches is refused — a commit made by `asf` itself included (B-0084).
# The marker makes a hook already running in THIS record return at once instead of nesting
# (B-0073); it names the record, so one inherited from another repo's hook run bypasses nothing.
top="$(git rev-parse --show-toplevel)" || exit 1
if [ "$ASF_HOOK_RUNNING" = "$top" ]; then
    exit 0
fi
export ASF_HOOK_RUNNING="$top"
cd "$top" || exit 1
staged="$(git diff --cached --name-only --diff-filter=ACMR)"
[ -n "$staged" ] || exit 0
echo "$staged" | tr '\\n' '\\0' | xargs -0 asf check || exit 1
# the redaction gate (F-0075): what `asf hooks install` checks for, so doctor calls this ours
exec asf redact --pre-commit
"""

#: The record's pre-push hook, written with :data:`PRE_COMMIT`: the redaction gate over what is
#: pushed, so a new record starts with both gate hooks in place (doctor's redaction-hooks row).
PRE_PUSH = """#!/bin/sh
# The record's pre-push hook, written by `asf init`: the redaction gate (F-0075).
exec asf redact --pre-push
"""

#: The line that marks a hook file as one `asf init` wrote — ASF's own, rewritten by
#: `asf hooks install` when an older `asf init` wrote it without the redaction gate.
INIT_MARKER = 'written by `asf init`'

README = """# The record

One markdown file per work item, in git, read by every `asf` command through `index.json`. The
schema and the tooling live in the `asf` package; this repo is the data. Every path, branch prefix
and limit is a key in the operator's product config (`~/.ASF/products/<name>.yaml`), never a
literal in a tool.

## Vocabulary

| Type | Folder | Id | Parent | What it is |
| --- | --- | --- | --- | --- |
| Epic | `epics/` | `E-nnnn` | — | a goal: a business outcome |
| Feature | `features/` | `F-nnnn` | Epic | one spec + one plan |
| User Story | `stories/` | `S-nnnn` | Feature | one requirement a customer can see |
| Task | `tasks/` | `T-nnnn` | Story or Feature | one plan task = one branch = one PR |
| Bug | `bugs/` | `B-nnnn` | Feature, Story or Epic | something broken, with a severity |
| Decision | `decisions/` | `D-nnnn` | — | a ruling, who made it and when |
| Rule | `rules/` | `R-nnnn` | — | a factory rule with a check script, or `enforced: false` |

| Folder | What |
| --- | --- |
| `inbox/` | raw thoughts, one file each; the groom pass turns them into cards |
| `groom/` | `YYYY-MM-DD.md`, generated daily; the operator answers one word per line |
| `releases/` | `YYYY-MM-DD-<sha>.md`, generated per prod deploy |
| `metrics/` | `ci/`, `sessions/`, `ticks/`, `events/` — JSONL, one line per event; `daily/` — generated md |
| `tools/checks/` | one read-only script per enforced Rule |

`index.json` — generated by `asf index`: every item's frontmatter and derived fields, keyed by id,
plus the record's `schema_version`. Scripts read this file, never the md files. Only `asf new`
mints an id; id = filename = link target.

## One item file

Frontmatter (typed fields, then `# ---- machine ----` and the fields the tick derives), then
`## Description`, `## Acceptance`, `## History`, and the `## Children` / `## Backlinks` sections
`asf index` rewrites. Links are `[[ID]]` in bodies, plain ids in frontmatter.

## State — typed intent, derived state

Typed by a person: title, description, acceptance, parent, priority, rank, decided, blockedBy,
removed, an Epic's `closed`, a Bug's severity. Derived by the tick from evidence: everything in the
machine block (`state: New | Active | Resolved | Closed`, `stage`, `evidence`, `cost`).

## Tooling

```
asf inbox --title "…"      file new work (the groom types it)
asf new story|task …      cut a Story or Task from a spec or plan
asf check                       validate (the pre-commit hook runs it)
asf index                       rewrite Children/Backlinks and index.json
asf roadmap | backlog | status  the views
asf schema-migrate              bring the record to the installed package's schema
.githooks/pre-commit            enabled with `git config core.hooksPath .githooks`
```
"""


def _git(args, cwd):
    try:
        out = subprocess.run(['git', *args], cwd=cwd, capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.TimeoutExpired):
        return None
    return out.stdout.strip() if out.returncode == 0 else None


# ---- discovery --------------------------------------------------------------

def slug_from_url(url):
    """``owner/name`` from an https or scp-style git url; None for a local path."""
    if not url:
        return None
    m = re.search(r'(?:[:/])([^/:]+)/([^/]+?)(?:\.git)?/?$', url)
    if not m or not re.match(r'^(https?|ssh|git)://|^[^/]+@[^:]+:', url):
        return None
    return f'{m.group(1)}/{m.group(2)}'


# where discovery looks for the specs/plans dirs, first hit wins: the usual places, then any
# `spec*`/`plan*` dir at any depth under docs/ — a product's own layout, found rather than named
SPECS_GLOBS = [DEFAULT_SPECS_DIR, 'specs', 'docs/**/specs', 'docs/**/spec*']
PLANS_GLOBS = [DEFAULT_PLANS_DIR, 'plans', 'docs/**/plans', 'docs/**/plan*']


def _first_dir(repo, patterns):
    for pat in patterns:
        hits = sorted(p for p in glob.glob(os.path.join(repo, pat), recursive=True) if os.path.isdir(p))
        if hits:
            return os.path.relpath(hits[0], repo)
    return None


def _test_command(repo):
    pkg = os.path.join(repo, 'package.json')
    if os.path.isfile(pkg):
        try:
            with open(pkg, encoding='utf-8') as f:
                scripts = json.load(f).get('scripts') or {}
        except (OSError, json.JSONDecodeError):
            scripts = {}
        if 'test' in scripts:
            for lock, tool in (('bun.lockb', 'bun'), ('bun.lock', 'bun'), ('pnpm-lock.yaml', 'pnpm'),
                               ('yarn.lock', 'yarn')):
                if os.path.exists(os.path.join(repo, lock)):
                    return f'{tool} run test'
            return 'npm test'
    py = os.path.join(repo, 'pyproject.toml')
    if os.path.isfile(py):
        with open(py, encoding='utf-8') as f:
            text = f.read()
        return 'pytest' if 'pytest' in text else 'python3 -m unittest discover -s tests'
    return None


def discover(name, repo, backlog):
    """The product config's keys, from the repo on disk. A value of None is a ``# TODO``."""
    repo = os.path.abspath(repo)
    branch = None
    head = _git(['symbolic-ref', '--short', 'refs/remotes/origin/HEAD'], repo)
    if head:
        branch = head.rsplit('/', 1)[-1]
    branch = branch or _git(['symbolic-ref', '--short', 'HEAD'], repo)
    ci = 'gh-actions' if os.path.isdir(os.path.join(repo, '.github', 'workflows')) else None
    return {
        'product': name,
        'repo_slug': slug_from_url(_git(['remote', 'get-url', 'origin'], repo)),
        'repo_dir': repo,
        'main': branch,
        'backlog_dir': os.path.abspath(backlog) if backlog else None,
        'specs_dir': _first_dir(repo, SPECS_GLOBS),
        'plans_dir': _first_dir(repo, PLANS_GLOBS),
        'ci_provider': ci,
        'test_command': _test_command(repo),
    }


def _line(key, value, indent=''):
    if value is None:
        return f'{indent}{key}:   # TODO: not discovered'
    return f'{indent}{key}: {value}'


def render_product_yaml(d):
    out = [f"# products/{d['product']}.yaml — written by `asf init` from discovery; fill every TODO.",
           _line('product', d['product']),
           _line('repo_slug', d['repo_slug']),
           _line('repo_dir', d['repo_dir']),
           _line('main', d['main']),
           _line('backlog_dir', d['backlog_dir']),
           'conventions:',
           _line('specs_dir', d['specs_dir'], '  '),
           _line('plans_dir', d['plans_dir'], '  '),
           '  branch_prefixes:']
    # written explicitly, every kind, so a product that overrides one prefix cannot silently
    # drop the rest — `conventions.all_prefixes()` only knows the kinds actually in the yaml
    # (B-0051: a kind missing here is a lane branch harvest never learns to look for)
    out += [_line(kind, DEFAULT_BRANCH_PREFIXES[kind], '    ')
           for kind in DEFAULT_BRANCH_PREFIXES if kind != 'legacy']
    out += ['ci:',
           _line('provider', d['ci_provider'], '  '),
           _line('test_command', d['test_command'], '  ')]
    return '\n'.join(out) + '\n'


# ---- the record -------------------------------------------------------------

def is_asf_record(backlog):
    return (all(os.path.isdir(os.path.join(backlog, f)) for f in ITEM_FOLDERS)
            and os.path.isfile(os.path.join(backlog, 'index.json')))


def lay_down(backlog, intake_dir=None):
    """The empty record. Never overwrites a file that is already there. Returns paths written."""
    written = []

    def put(rel, text, mode=None):
        path = os.path.join(backlog, rel)
        if os.path.exists(path):
            return
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(text)
        if mode:
            os.chmod(path, mode)
        written.append(rel)

    for folder in ITEM_FOLDERS + STREAM_FOLDERS + (intake_dir or DEFAULT_INTAKE_DIR,):
        put(os.path.join(folder, '.gitkeep'), '')
    put('README.md', README)
    put(os.path.join('.githooks', 'pre-commit'), PRE_COMMIT, 0o755)
    put(os.path.join('.githooks', 'pre-push'), PRE_PUSH, 0o755)
    put('index.json', json.dumps({'items': {}, 'schema_version': schema.SCHEMA_VERSION},
                                 indent=2, sort_keys=True) + '\n')
    if _git(['rev-parse', '--is-inside-work-tree'], backlog) != 'true':
        _git(['init', '-q'], backlog)
    if _git(['rev-parse', '--show-toplevel'], backlog) == os.path.realpath(backlog):
        _git(['config', 'core.hooksPath', '.githooks'], backlog)
    return written


def _count_items(backlog):
    with open(os.path.join(backlog, 'index.json'), encoding='utf-8') as f:
        return len(json.load(f).get('items') or {})


def cmd_init(args):
    name = args.product
    path = env.product_path(name)
    existing = env.load_file(path) if os.path.isfile(path) else None
    repo = args.repo or (existing or {}).get('repo_dir') or os.getcwd()
    repo = os.path.expanduser(repo)
    backlog = args.backlog or (existing or {}).get('backlog_dir')
    backlog = os.path.expanduser(backlog) if backlog else None

    discovered = render_product_yaml(discover(name, repo, backlog))
    if existing is not None:
        with open(path, encoding='utf-8') as f:
            current = f.read()
        diff = list(difflib.unified_diff(current.splitlines(True), discovered.splitlines(True),
                                         fromfile=path, tofile=f'{path} (discovered)'))
        print(f'init: {path} exists — left as is' + ('; discovery would change:' if diff else ''))
        sys.stdout.writelines(diff)
    else:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(discovered)
        print(f'init: wrote {path}')

    if not backlog:
        print('NEEDS OPERATOR: no backlog dir for the record — asf init --product '
              f'{name} --backlog DIR', file=sys.stderr)
        return 2

    from asf.record.index import do_index
    # `asf index` rewrites index.json without the stamp, so the stamp is read before and
    # re-applied after: an adopted record keeps an older stamp (schema-migrate's job), an
    # unstamped one gets the package's.
    if os.path.isdir(backlog) and is_asf_record(backlog):
        version = schema.record_version(backlog) or schema.SCHEMA_VERSION
        rc = do_index(backlog)
        schema.stamp(backlog, version)
        print(f'init: adopted {_count_items(backlog)} items')
    else:
        os.makedirs(backlog, exist_ok=True)
        conventions = env.Product(name, env.load_file(path)).conventions
        written = lay_down(backlog, intake_dir=conventions.intake_dir)
        rc = do_index(backlog)
        schema.stamp(backlog, schema.SCHEMA_VERSION)
        print(f'init: laid down a new record at {backlog} ({len(written)} files)')
    if rc:
        return rc

    from asf.views import roadmap
    product = env.Product(name, env.load_file(path))
    # the push gate comes with adoption, not as a second command a human must remember: a repo
    # ASF has adopted and has no gate on is exactly what F-0075 exists to prevent, and `doctor`
    # would report it red the moment init finished.
    from asf import hooks as hooks_mod
    ok, detail = hooks_mod.ensure_git_hooks(product)
    print(f"init: git hooks {'in place' if ok else 'NOT installed'}" + (f' — {detail}' if detail else ''))
    print(roadmap.render(backlog, product), end='')
    return 0


def register(subparsers):
    p = subparsers.add_parser('init', help="adopt a product: its config, its record, its first roadmap")
    p.add_argument('--product', required=True)
    p.add_argument('--repo', help='the product repo (default: the current directory)')
    p.add_argument('--backlog', help="the record's directory (default: backlog_dir from the config)")
    p.set_defaults(run=cmd_init)
    return p


def register_commands(subparsers):
    """``init``, ``schema-migrate``, ``upgrade``, ``hooks``, ``hook`` — each parser carries its
    handler as ``args.run(args)``."""
    from asf import hooks, upgrade
    register(subparsers)
    schema.register(subparsers)
    upgrade.register(subparsers)
    hooks.register(subparsers)
