"""asf.harvest.transplant — approved content moved onto the trunk by the lane, never a session.

Two items of one product burned ~35 adjudicate/correct sessions between them (2026-09-25..29):
every review approved the CONTENT, and every hold after it was git mechanics — trunk history
under the branch, a reword, a rebase that conflicted in a generated doc, the review files and
``.files-block.json`` riding along. A session cannot fix that by thinking; the lane can by
construction: it takes the files the approved head carries and puts them on a fresh trunk.

**The case** (:meth:`asf.harvest.lane.Lane.transplant_case`): the item's newest review approved
the content on some head ``H`` (:func:`approval` — read as approved by
:mod:`asf.evidence.review`, no C item open), and the branch has since been held only by
mechanical causes (:func:`mechanical`: a conflict, a failed rebase, trunk copies, naming, an
unpushed end, a hook or gate red only on generated files or factory artifacts) — or sits STALE
for being unmoved. Never while a session runs on the item, never past an operator park, an
``asf correct`` instruction or ruling, a reset, or :data:`CAP` transplants of one approved head.

**The transplant** (:func:`plan`, :func:`build`): a new commit on ``origin/<trunk>`` carrying
``H``'s change to exactly the files the Task's own commits changed — ``H``'s version of each the
trunk has not touched since, else ``H``'s change three-way merged onto the trunk's version
(:func:`place`: never a trunk change dropped; a conflict there is content, left to a session).
Not the review files, not ``.files-block.json`` or another factory artifact (:func:`artifact`),
and not a generated file
(:func:`generated`): one the product declares under ``conventions.generated`` is regenerated by
its ``run`` command; one it does not declare (its own header says it is generated) keeps the
trunk's version and the gate says. The product's ``pre_push_check`` runs on it (the head sits
on the trunk, so it is #624's trunk-merge parity), and it is pushed once over a lease with the
old tip archived (:meth:`~asf.harvest.lane.Lane.publish_rebuilt`).

**The approval is bound to the content** (:func:`same_diff`): it is carried to the new head
only when the transplant's diff over the trunk, for those files, is ``H``'s own diff for them
(``git patch-id``); otherwise the head goes to a fresh review round like any new head.
"""
import fnmatch
import json
import os
import re
import shutil
import subprocess
import tempfile

from asf.evidence import review as review_mod
from asf.harvest import harvest as H
from asf.workers import lifecycle

#: Transplants of one approved head of one item before the lane stops trying (the relaunch
#: cap's number): a transplant that comes back to a mechanical hold twice is not a third.
CAP = 2
#: Under the state dir: one line per transplant made (or refused by the pre-push check).
LEDGER = 'transplants.jsonl'
#: Under the state dir: the throwaway checkouts a transplant is built in.
WORK_DIR = 'transplant'
#: Factory artifacts never transplanted, wherever they sit (beside the reviews and reports dirs).
ARTIFACT_NAMES = ('.files-block.json',)
#: A generated file's own header (first :data:`MARK_BYTES`): ``# Drift report (generated)``,
#: ``Do not edit by hand``, ``@generated``, ``auto-generated``.
GENERATED_MARK_RE = re.compile(r'\(generated\)|do not edit|@generated|auto-?generated', re.I)
MARK_BYTES = 800
#: The correction kinds that are git mechanics whatever they name.
MECHANICAL_KINDS = (lifecycle.NAMING, lifecycle.COPIES, 'merge', 'conflict',
                    lifecycle.REBASE_CONFLICT, lifecycle.UNPUSHED)
#: The correction kinds that are mechanics only when every path they name is a generated file
#: or a factory artifact (a docs-check red on a regenerated report).
GENERATED_KINDS = ('hook refused', 'gate')
#: A repo path in a correction's text.
PATH_RE = re.compile(r'(?<![\w/.-])((?:[\w@.-]+/)*[\w@-][\w@.-]*\.[A-Za-z0-9]+)(?::\d+)?')
#: How long a declared regen command may run.
REGEN_TIMEOUT_S = 900
#: The trailer naming the approved head a transplant carries.
TRAILER = 'ASF-Transplant'


def _git(repo, *args, **kw):
    return H.sh(['git', *args], cwd=repo, **kw)


def rev(repo, ref):
    """The full sha of ``ref`` (a commit), or ''."""
    return _git(repo, 'rev-parse', '--verify', '-q', f'{ref}^{{commit}}').stdout.strip()


# ---- what a file is ---------------------------------------------------------------------------

def artifact(conv, path):
    """True when ``path`` is a factory artifact: a review (``reviews_dir``), a report
    (``reports_dir``), or one of :data:`ARTIFACT_NAMES`."""
    if os.path.basename(path) in ARTIFACT_NAMES:
        return True
    for key in ('reviews_dir', 'reports_dir'):
        d = (conv.get(key) if conv is not None else None) or ''
        if d and (path == d or path.startswith(d.rstrip('/') + '/')):
            return True
    return False


def declared(conv):
    """``[(globs, run)]`` of ``conventions.generated``: a list of ``{paths: [glob, …] | path:
    glob, run: command}`` — the files a command regenerates. Anything else is no entry."""
    out = []
    for e in (conv.get('generated') if conv is not None else None) or ():
        if not isinstance(e, dict):
            continue
        globs = e.get('paths') or e.get('path') or ()
        globs = [globs] if isinstance(globs, str) else [g for g in globs if isinstance(g, str)]
        if globs:
            out.append((globs, str(e.get('run') or '').strip()))
    return out


def rule_of(conv, path):
    """The ``(globs, run)`` entry of :func:`declared` that names ``path``, or None."""
    for globs, run in declared(conv):
        if any(fnmatch.fnmatchcase(path, g) or path == g for g in globs):
            return globs, run
    return None


def marked(repo, revs, path):
    """True when ``path``'s own header says it is generated at any of ``revs``."""
    for r in revs:
        out = _git(repo, 'cat-file', '-p', f'{r}:{path}')
        if out.returncode == 0 and GENERATED_MARK_RE.search(out.stdout[:MARK_BYTES]):
            return True
    return False


def generated(repo, conv, path, revs):
    """True when ``path`` is a generated file: declared (:func:`rule_of`) or marked
    (:func:`marked`) at one of ``revs``."""
    return rule_of(conv, path) is not None or marked(repo, revs, path)


def mechanical(corr, is_generated=None):
    """True when the pending correction ``corr`` is git mechanics (:data:`MECHANICAL_KINDS`), or
    a hook/gate red (:data:`GENERATED_KINDS`) whose every named path ``is_generated(path)`` calls
    generated or an artifact. An operator's instruction, a park or a security flag is never."""
    corr = corr or {}
    kind = corr.get('kind')
    if corr.get('parked') or corr.get('operator_flagged') or corr.get('operator_ruling'):
        return False
    if kind in MECHANICAL_KINDS:
        return True
    if kind in GENERATED_KINDS and is_generated is not None:
        paths = {m.group(1) for m in PATH_RE.finditer(corr.get('text') or '')}
        return bool(paths) and all(is_generated(p) for p in paths)
    return False


# ---- the approval -----------------------------------------------------------------------------

def approval(repo, conv, ref, item, required=(), store=None):
    """The approval of ``item``'s content: ``{head, path, round, customer_row}`` — ``head`` the
    full sha of the code the newest review of ``ref`` approved — or None when the newest review
    does not read approved (:mod:`asf.evidence.review`), keeps a C item open, or names a head
    the repo does not hold. A review with no ``head:`` line approved the commit it was added on
    (nothing outside the reviews dir is in a review commit)."""
    rv = review_mod.review_at(repo, conv, ref, item, required, store=store)
    if not rv or rv.get('verdict') != review_mod.APPROVED:
        return None
    body = rv.get('body') or ''
    if review_mod.c_items(body) and not review_mod.asks_nothing(body):
        return None
    head = ''
    if rv.get('head'):
        head = rev(repo, rv['head'])
    elif not rv.get('stored'):
        head = _git(repo, 'log', '-1', '--format=%H', ref, '--', rv['path']).stdout.strip()
    if not head:
        return None
    from asf import customer_content
    return {'head': head, 'path': rv.get('path'), 'round': int(rv.get('round') or 0),
            'customer_row': customer_content.has_customer_row(body)}


# ---- the plan and the build -------------------------------------------------------------------

def own_files(repo, trunk_ref, head):
    """``(base, files)``: the merge-base of ``trunk_ref`` and ``head``, and the files ``head``'s
    own commits changed — no merge, no copy of a trunk commit (``--cherry-mark`` ``=``) — whose
    content at ``head`` is not the base's (a change the commits made and undid is none)."""
    base = _git(repo, 'merge-base', trunk_ref, head).stdout.strip()
    if not base:
        return '', []
    r = _git(repo, 'log', '--no-merges', '--cherry-mark', '--right-only', '--format=%m %H',
             f'{trunk_ref}...{head}')
    own = [l.split()[1] for l in r.stdout.splitlines() if l.startswith('> ')]
    files = []
    for sha in own:
        d = _git(repo, 'diff-tree', '--no-commit-id', '--name-only', '-r', sha)
        files.extend(p for p in d.stdout.splitlines() if p and p not in files)
    if not files:
        return base, []
    changed = set(_git(repo, 'diff', '--name-only', base, head, '--', *files).stdout.split())
    return base, sorted(f for f in files if f in changed)


def plan(repo, conv, trunk_ref, head):
    """What a transplant of ``head`` onto ``trunk_ref`` does: ``{base, copy, regen, trunk,
    artifacts}`` — ``copy`` the files taken from ``head``, ``regen`` ``{command: [globs]}`` the
    declared generated files and the commands that write them, ``trunk`` the generated files no
    command regenerates (the trunk's version stands), ``artifacts`` the factory's files left
    out."""
    base, files = own_files(repo, trunk_ref, head)
    out = {'base': base, 'copy': [], 'regen': {}, 'trunk': [], 'artifacts': []}
    for f in files:
        if artifact(conv, f):
            out['artifacts'].append(f)
            continue
        rule = rule_of(conv, f)
        if rule and rule[1]:
            out['regen'].setdefault(rule[1], [])
            out['regen'][rule[1]].extend(g for g in rule[0] if g not in out['regen'][rule[1]])
        elif rule or marked(repo, (head, trunk_ref), f):
            out['trunk'].append(f)
        else:
            out['copy'].append(f)
    return out


def _shell(command, cwd, timeout):
    p = subprocess.run(command, shell=True, cwd=cwd, env=H.clean_env(dict(os.environ)),
                       stdin=subprocess.DEVNULL, capture_output=True, text=True,
                       timeout=timeout)
    return p.returncode, (p.stdout or '') + (p.stderr or '')


def _blob(repo, rev_, path):
    """``path``'s blob id at ``rev_``, or '' when ``rev_`` has no such file."""
    r = _git(repo, 'rev-parse', '--verify', '-q', f'{rev_}:{path}')
    return r.stdout.strip() if r.returncode == 0 else ''


def place(repo, wt, base, trunk, head, path):
    """Put the approved ``head``'s change to ``path`` into the checkout ``wt`` (at ``trunk``):
    ``head``'s version when the trunk has not touched the file since ``base`` (or already holds
    ``head``'s); else ``head``'s own change three-way merged onto the trunk's version (``git
    merge-file``) — never a trunk change dropped. True when placed, False on a conflict (both
    changed the same lines, or one deleted what the other changed)."""
    b, t, h = (_blob(repo, base, path), _blob(repo, trunk, path), _blob(repo, head, path))
    if t == h:
        return True
    if t == b:
        r = (_git(wt, 'checkout', head, '--', path) if h
             else _git(wt, 'rm', '-q', '--ignore-unmatch', '--', path))
        return r.returncode == 0
    if not (b and t and h):
        return False  # added on both sides, or deleted on one and changed on the other
    tmp = tempfile.mkdtemp(prefix='merge-', dir=os.path.dirname(wt))
    try:
        files = []
        for name, blob in (('base', b), ('head', h)):
            out = os.path.join(tmp, name)
            with open(out, 'wb') as fh:
                fh.write(subprocess.run(['git', 'cat-file', 'blob', blob], cwd=repo,
                                        capture_output=True).stdout)
            files.append(out)
        r = subprocess.run(['git', 'merge-file', '-p', os.path.join(wt, path), *files],
                           cwd=wt, capture_output=True)
        if r.returncode != 0:
            return False
        with open(os.path.join(wt, path), 'wb') as fh:
            fh.write(r.stdout)
        return _git(wt, 'add', '--', path).returncode == 0
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def build(repo, state_dir, trunk_ref, head, the_plan, message, ident, setup=None,
          timeout=REGEN_TIMEOUT_S):
    """``(sha, why, conflicts)``: one commit on ``trunk_ref`` with the approved ``head``'s
    change to each of ``the_plan['copy']`` (:func:`place`), the declared generated files
    regenerated by their commands (after ``setup``, the product's ``worktree_setup``) — built in
    a throwaway detached checkout under ``<state>/transplant/``, committed by ``git
    commit-tree`` with ``ident``'s author and committer and ``message``, no hook run, nothing
    pushed. ``sha`` '' with ``why`` the one line when it could not be built; ``conflicts`` the
    files whose approved change conflicts with the trunk's since (no commit then)."""
    parent = rev(repo, trunk_ref)
    if not parent:
        return '', f'{trunk_ref} unreadable', []
    holder = os.path.join(state_dir, WORK_DIR)
    try:
        os.makedirs(holder, exist_ok=True)
        path = tempfile.mkdtemp(prefix='wt-', dir=holder)
        os.rmdir(path)
    except OSError as e:
        return '', f'no checkout to build in: {e}', []
    add = _git(repo, 'worktree', 'add', '-q', '--detach', path, parent)
    if add.returncode != 0:
        shutil.rmtree(path, ignore_errors=True)
        return '', f'no checkout of {parent[:9]}: {H.tail(add.stderr)}', []
    try:
        conflicts = [f for f in the_plan['copy']
                     if not place(repo, path, the_plan['base'], parent, head, f)]
        if conflicts:
            return '', ('the approved change conflicts with the trunk\'s since in '
                        f'{", ".join(conflicts)}'), conflicts
        if the_plan['regen']:
            for what, cmd in (('worktree_setup', setup),) + tuple(
                    ('regen', c) for c in the_plan['regen']):
                if not cmd:
                    continue
                try:
                    rc, out = _shell(cmd, path, timeout)
                except subprocess.TimeoutExpired:
                    rc, out = None, f'timed out after {timeout}s'
                if rc != 0:
                    lines = [l for l in out.splitlines() if l.strip()][-5:]
                    return '', f'`{cmd}` ({what}) failed: ' + ' | '.join(lines), []
            globs = [g for gs in the_plan['regen'].values() for g in gs]
            st = _git(path, 'status', '--porcelain', '-z', '--no-renames',
                      '--untracked-files=all')
            made = [e[3:] for e in st.stdout.split('\0') if len(e) > 3]
            fresh = [p for p in made if any(fnmatch.fnmatchcase(p, g) or p == g for g in globs)]
            r = _git(path, 'add', '-A', '--', *fresh) if fresh else None
            if r is not None and r.returncode != 0:
                return '', f'git add of the regenerated files failed: {H.tail(r.stderr)}', []
        tree = _git(path, 'write-tree').stdout.strip()
        if not tree:
            return '', 'git write-tree failed', []
        if tree == _git(repo, 'rev-parse', f'{parent}^{{tree}}').stdout.strip():
            return '', f'nothing to transplant: {trunk_ref} already holds the approved change', []
        made = subprocess.run(['git', 'commit-tree', tree, '-p', parent], input=message,
                              cwd=repo, capture_output=True, text=True,
                              env=H.clean_env(dict(os.environ, **ident)))
        sha = made.stdout.strip()
        if made.returncode != 0 or not sha:
            return '', f'git commit-tree failed: {H.tail(made.stderr)}', []
        return sha, '', []
    finally:
        _git(repo, 'worktree', 'remove', '--force', path)
        shutil.rmtree(path, ignore_errors=True)


def _patch_id(repo, a, b, files):
    if not files:
        return None
    d = _git(repo, 'diff', '-U0', '--full-index', a, b, '--', *files)
    if d.returncode != 0 or not d.stdout:
        return None
    p = subprocess.run(['git', 'patch-id', '--stable'], cwd=repo, input=d.stdout,
                       capture_output=True, text=True)
    return (p.stdout.split() or [None])[0] if p.returncode == 0 else None


def same_diff(repo, base, head, trunk_ref, new, files):
    """True when the transplant ``new``'s diff over ``trunk_ref`` for ``files`` is the approved
    ``head``'s own diff over its ``base`` for them — the same lines removed and added in the
    same files, whatever the line offsets and the unchanged lines around them (``git diff -U0``
    through ``git patch-id --stable``): the trunk moving code beside the change is the gate's to
    judge, not a new change to review. The approval is carried only then."""
    mine = _patch_id(repo, base, head, files)
    return bool(mine) and mine == _patch_id(repo, trunk_ref, new, files)


# ---- the message ------------------------------------------------------------------------------

def ident_of(repo, sha):
    """``GIT_AUTHOR_*``/``GIT_COMMITTER_*`` for a transplant of ``sha``: its author, both."""
    r = _git(repo, 'log', '-1', '--format=%an%x00%ae', sha)
    name, _, email = r.stdout.rstrip('\n').partition('\x00')
    name, email = name or 'asf', email or 'asf@localhost'
    return {'GIT_AUTHOR_NAME': name, 'GIT_AUTHOR_EMAIL': email,
            'GIT_COMMITTER_NAME': name, 'GIT_COMMITTER_EMAIL': email}


def subject_of(repo, trunk_ref, head, item, word='task'):
    """The subject of ``head``'s oldest own commit that names ``item``, else
    ``<word>(<item>): …``."""
    r = _git(repo, 'log', '--reverse', '--no-merges', '--format=%s', f'{trunk_ref}..{head}')
    for s in r.stdout.splitlines():
        if item and re.search(rf'\b{re.escape(item)}\b', s):
            return s
    return f'{word}({item}): the approved change'


def message(subject, item, head, review, trunk, the_plan):
    """The transplant's commit message: the subject, what was carried and from where, and the
    :data:`TRAILER` naming the approved head."""
    lines = [subject, '',
             f'The factory lane transplanted the content {review} approved at {head[:9]} onto '
             f'origin/{trunk}: {len(the_plan["copy"])} file(s) carrying the approved change, '
             f'without its history.']
    if the_plan['regen']:
        lines.append('Regenerated: ' + ', '.join(sorted(the_plan['regen'])) + '.')
    if the_plan['trunk']:
        lines.append(f'Generated, kept at origin/{trunk}: ' + ', '.join(the_plan['trunk']) + '.')
    if the_plan['artifacts']:
        lines.append('Left out (factory artifacts): ' + ', '.join(the_plan['artifacts']) + '.')
    lines += ['', f'{TRAILER}: {head}']
    return '\n'.join(lines) + '\n'


# ---- the ledger -------------------------------------------------------------------------------

def ledger_path(state_dir):
    return os.path.join(state_dir, LEDGER)


def count(state_dir, item, head):
    """How many transplants of ``item``'s approved ``head`` the ledger holds."""
    n = 0
    try:
        with open(ledger_path(state_dir), encoding='utf-8') as fh:
            for line in fh:
                try:
                    rec = json.loads(line)
                except ValueError:
                    continue
                n += rec.get('item') == item and rec.get('from') == head
    except OSError:
        return 0
    return n


def note(state_dir, **rec):
    with open(ledger_path(state_dir), 'a', encoding='utf-8') as fh:
        fh.write(json.dumps(rec, sort_keys=True) + '\n')


def carried_review(tp):
    """The review a transplant carries to its head (``tp``: the lane record's ``transplant``)."""
    return {'round': tp.get('round') or 0, 'verdict': review_mod.APPROVED, 'text': 'approved',
            'path': tp.get('review'), 'head': tp.get('head'), 'current': True,
            'customer_row': bool(tp.get('customer_row')), 'carried': tp.get('from')}
