"""asf.tick.shadow_diff — ``asf shadow-diff``: the cutover gate.

Compares a product's shadow tick output (``asf tick --shadow``'s ``index.json`` and
``tables/*.md``) against a reference directory of the same shape — an ``index.json`` and a
``tables/`` directory holding the pre-``asf`` tools' output, generated by hand the same minute
the shadow tick ran (see this repo's shadow-tick report for the exact commands). Two clean
consecutive shadow ticks with an empty ``shadow-diff`` is the cutover signal.

``index.json`` is compared with ``generated``, ``updated`` and ``stage_since`` stripped from
every item (those churn every run and carry no information about correctness). Each table is
compared with its first line (the stamp — a clock time or ``index.json generated ...``) dropped.
"""
import argparse
import difflib
import json
import os

TIMESTAMP_KEYS = {'generated', 'updated', 'stage_since'}
TABLE_NAMES = ['roadmap', 'backlog', 'parity', 'prod', 'sessions', 'status']


def _strip_timestamps(obj):
    if isinstance(obj, dict):
        return {k: _strip_timestamps(v) for k, v in obj.items() if k not in TIMESTAMP_KEYS}
    if isinstance(obj, list):
        return [_strip_timestamps(v) for v in obj]
    return obj


def diff_index(shadow_root, ref_root):
    shadow_path = os.path.join(shadow_root, 'index.json')
    ref_path = os.path.join(ref_root, 'index.json')
    with open(shadow_path, encoding='utf-8') as f:
        shadow = _strip_timestamps(json.load(f))
    with open(ref_path, encoding='utf-8') as f:
        ref = _strip_timestamps(json.load(f))
    a = json.dumps(shadow, indent=2, sort_keys=True).splitlines(keepends=True)
    b = json.dumps(ref, indent=2, sort_keys=True).splitlines(keepends=True)
    return list(difflib.unified_diff(b, a, fromfile='ref/index.json', tofile='shadow/index.json'))


def _drop_stamp(text):
    lines = text.splitlines(keepends=True)
    return lines[1:] if lines else lines


def diff_table(shadow_root, ref_root, name):
    shadow_path = os.path.join(shadow_root, 'tables', f'{name}.md')
    ref_path = os.path.join(ref_root, 'tables', f'{name}.md')
    if not os.path.exists(shadow_path) or not os.path.exists(ref_path):
        return [f"-- {name}: missing ({'shadow' if not os.path.exists(shadow_path) else 'ref'} "
                f"has no tables/{name}.md)\n"]
    with open(shadow_path, encoding='utf-8') as f:
        a = _drop_stamp(f.read())
    with open(ref_path, encoding='utf-8') as f:
        b = _drop_stamp(f.read())
    return list(difflib.unified_diff(b, a, fromfile=f'ref/tables/{name}.md', tofile=f'shadow/tables/{name}.md'))


def run(shadow_root, ref_root, tables=TABLE_NAMES):
    out = []
    index_diff = diff_index(shadow_root, ref_root)
    if index_diff:
        out.append(''.join(index_diff))
    for name in tables:
        d = diff_table(shadow_root, ref_root, name)
        if d:
            out.append(''.join(d))
    return out


def cmd_shadow_diff(args, root=None):
    from asf import env
    from asf.tick.shadow import shadow_dir

    product = env.load_product(getattr(args, 'product', None))
    shadow_root = shadow_dir(product)
    ref_root = args.ref

    diffs = run(shadow_root, ref_root)
    if not diffs:
        print("shadow-diff: clean — index.json and every table match")
        return 0
    for d in diffs:
        print(d)
    return 1


def build_parser(sub):
    p = sub.add_parser('shadow-diff', help="diff a product's shadow tick against a reference clone/tables dir")
    p.add_argument('--ref', required=True,
                   help='reference dir: an index.json plus a tables/ dir of the pre-asf tools’ output')
    return p
