#!/usr/bin/env bash
# tools/ab-ci-queue.sh <product> <venvA> <venvB> — the CI start queue's decisions, pinned venv
# vs candidate, at the same minute.
#
# Runs `asf ci queue --product <p>` — the read-only view, never `--apply` — under each venv's own
# interpreter (no PYTHONPATH, cwd /), back to back, and diffs the two. venvA / venvB as in
# tools/ab-lib.sh (`pin`, a dir, a venv name, a sha).
# Exit 0 when the two print the same decisions, 1 when they differ, 2 when a run fails.
# Env: ASF_HOME  the asf home (default ~/.ASF)
set -uo pipefail

product="${1:-}"; a="${2:-}"; b="${3:-}"
[ -n "$product" ] && [ -n "$a" ] && [ -n "$b" ] || {
  echo "usage: ab-ci-queue.sh <product> <venvA> <venvB>" >&2; exit 2; }
here=$(cd "$(dirname "$0")" && pwd -P)
. "$here/ab-lib.sh"
venv_a=$(ab_venv "$product" "$a") || exit 2
venv_b=$(ab_venv "$product" "$b") || exit 2

work=$(mktemp -d "${TMPDIR:-/tmp}/asf-ab-ci-queue.XXXXXX")
trap 'rm -rf "$work"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

view() {  # <venv> <out>
  (cd / && env -u PYTHONPATH -u PYTHONHOME "$1/bin/python" -m asf.cli ci queue \
     --product "$product" >"$2" 2>&1)
}
view "$venv_a" "$work/a"; rc_a=$?
view "$venv_b" "$work/b"; rc_b=$?
echo "A $venv_a  (exit $rc_a)"
echo "B $venv_b  (exit $rc_b)"
if [ "$rc_a" != 0 ] || [ "$rc_b" != 0 ]; then
  echo "ab-ci-queue: a run failed — no verdict"; tail -n 5 "$work/a" "$work/b"; exit 2
fi
# a stamp line names its venv and the minute: not a decision
for f in a b; do grep -v '^— generated by ' "$work/$f" >"$work/$f.v"; done
if diff -u --label A --label B "$work/a.v" "$work/b.v"; then
  echo "identical ($(wc -l <"$work/a.v" | tr -d ' ') lines)"
  exit 0
fi
exit 1
