#!/usr/bin/env bash
# tools/ab-dry-run.sh <product> <venvA> <venvB> — the pinned venv and a candidate, side by side.
#
# Makes ONE frozen copy of the product's state, then runs `asf tick --dry-run` under each venv's
# own interpreter against that same copy, back to back (`--with-venv`, `--state-copy`;
# asf.tick.dry_run): read-only — nothing is pushed, opened, merged or launched. Diffs the
# `== lane`, `== wave` and `== harvest` sections (temp paths normalised) and prints the diff.
#
#   venvA / venvB   `pin`, a venv dir, a venv name under pipx's venvs dir, or a sha (the
#                   product's own asf-factory-<product>-<sha7>) — see tools/ab-lib.sh
# Exit 0 when B adds no `would …` line A lacks (the diff, if any, is printed), 1 when it does,
# 2 when a run fails or a venv cannot be found.
# Env: ASF_HOME     the asf home (default ~/.ASF)
#      ASF_AB_CLI   the command that orchestrates the runs (default: python3 -m asf.cli from
#                   this checkout — it needs --with-venv; the venvs themselves need not)
#      ASF_AB_KEEP  a directory to keep both outputs in (default: removed)
set -uo pipefail

product="${1:-}"; a="${2:-}"; b="${3:-}"
[ -n "$product" ] && [ -n "$a" ] && [ -n "$b" ] || {
  echo "usage: ab-dry-run.sh <product> <venvA> <venvB>" >&2; exit 2; }
here=$(cd "$(dirname "$0")" && pwd -P)
. "$here/ab-lib.sh"
repo=$(dirname "$here")
venv_a=$(ab_venv "$product" "$a") || exit 2
venv_b=$(ab_venv "$product" "$b") || exit 2

work=$(mktemp -d "${TMPDIR:-/tmp}/asf-ab-dry-run.XXXXXX")
trap 'rm -rf "$work"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
snap="$work/state"

orchestrate() {  # <venv> <out>
  if [ -n "${ASF_AB_CLI:-}" ]; then
    $ASF_AB_CLI tick --dry-run --product "$product" --state-copy "$snap" --with-venv "$1" >"$2"
  else
    PYTHONPATH="$repo" python3 -m asf.cli tick --dry-run --product "$product" \
      --state-copy "$snap" --with-venv "$1" >"$2"
  fi
}

# the lane / wave / harvest sections, temp paths normalised
sections() {
  awk '/^== /{keep = ($2 == "lane" || $2 == "wave" || $2 == "harvest")} keep' "$1" |
    grep -v '^— generated by ' | sed -E 's#[^ ]*asf-dry-run[-A-Za-z0-9_.]*(/[^ ]*)?#<tmp>#g'
}

date_a=$(date +%H:%M:%S)
orchestrate "$venv_a" "$work/a.out"; rc_a=$?
date_b=$(date +%H:%M:%S)
orchestrate "$venv_b" "$work/b.out"; rc_b=$?
echo "A $venv_a  ($date_a, exit $rc_a)"
echo "B $venv_b  ($date_b, exit $rc_b)"
if [ -n "${ASF_AB_KEEP:-}" ]; then mkdir -p "$ASF_AB_KEEP" && cp "$work/a.out" "$work/b.out" "$ASF_AB_KEEP/"; fi
if [ "$rc_a" != 0 ] || [ "$rc_b" != 0 ]; then
  echo "ab-dry-run: a run failed — no verdict"; tail -n 5 "$work/a.out" "$work/b.out"; exit 2
fi

sections "$work/a.out" >"$work/a.sec"
sections "$work/b.out" >"$work/b.sec"
if diff -u --label A --label B "$work/a.sec" "$work/b.sec" >"$work/diff"; then
  echo "identical ($(wc -l <"$work/a.sec" | tr -d ' ') section lines)"
  exit 0
fi
cat "$work/diff"
new=$(comm -13 <(grep 'would ' "$work/a.sec" | sort -u) <(grep 'would ' "$work/b.sec" | sort -u))
if [ -n "$new" ]; then
  echo "NEW would-lines under B:"; printf '%s\n' "$new" | sed 's/^/  /'
  exit 1
fi
echo "differs, but B adds no would-line"
exit 0
