#!/usr/bin/env bash
# tools/check_conventions.sh — no product *convention* in the code: no branch prefix, document
# tree, file name or item id that one product uses and another does not. Every one of them is a
# field of asf.conventions.Conventions, read from the product yaml.
#
# Fails if any `asf/**/*.py` matches a pattern in tools/forbidden-conventions.txt or generated by
# `python3 -m asf.conventions --forbidden` (one anchored regex per path-shaped default: a copy of
# a default is a convention in code too). Four files are exempt by construction:
#   asf/conventions.py              the defaults themselves live there, documented, one per field
#   asf/metrics/import_sessions.py  an adapter for a foreign log format: its literals describe
#                                   that file's shape, not this factory's conventions
#   asf/hooks.py                    an adapter for the worker runtime's own settings file: the
#                                   path is the runtime's convention, not a product's
#   asf/console_perms.py            the console's own allow list (B-0131): `.claude/settings.json`
#                                   is the runtime's own path, and `tools/install.sh` this
#                                   factory's own fixed installer — neither is a product's
# `~/.ASF` is allowed everywhere — that is the operator's own directory, not a product's.
#
#   check_conventions.sh                     check the package
#   check_conventions.sh --exclude <path>    skip one more file (repeatable)
#   check_conventions.sh --print-patterns    print the merged pattern list and exit, no scanning
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(git rev-parse --show-toplevel)"
PATTERNS_FILE="$HERE/forbidden-conventions.txt"

excludes=(
  "asf/conventions.py"
  "asf/metrics/import_sessions.py"
  "asf/hooks.py"
  "asf/console_perms.py"
)

print_only=0
while [ $# -gt 0 ]; do
  case "$1" in
    --exclude)
      excludes+=("$2")
      shift 2
      ;;
    --print-patterns)
      print_only=1
      shift
      ;;
    *)
      echo "usage: check_conventions.sh [--exclude <path>]... [--print-patterns]" >&2
      exit 2
      ;;
  esac
done

if [ ! -f "$PATTERNS_FILE" ]; then
  echo "check_conventions: missing $PATTERNS_FILE" >&2
  exit 2
fi

patterns=()
while IFS= read -r line; do
  line="${line%%#*}"
  line="$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
  [ -z "$line" ] && continue
  patterns+=("$line")
done < "$PATTERNS_FILE"

if [ ${#patterns[@]} -eq 0 ]; then
  echo "check_conventions: no patterns loaded" >&2
  exit 2
fi

# The second pattern source: one anchored regex per path-shaped default in asf.conventions
# itself, generated at run time — a copy of a default is a convention in code too, and this way
# the list can never drift from the module that owns the defaults.
gen_status=0
generated="$(PYTHONPATH="$ROOT" python3 -m asf.conventions --forbidden)" || gen_status=$?
if [ "$gen_status" -ne 0 ] || [ -z "$generated" ]; then
  echo "check_conventions: could not read the defaults from asf.conventions" >&2
  exit 2
fi
while IFS= read -r line; do
  [ -n "$line" ] && patterns+=("$line")
done <<< "$generated"

if [ "$print_only" -eq 1 ]; then
  printf '%s\n' "${patterns[@]}"
  exit 0
fi

cd "$ROOT"

found=0
while IFS= read -r f; do
  [ -z "$f" ] && continue
  [ -f "$f" ] || continue
  skip=0
  for e in "${excludes[@]}"; do
    [ "$f" = "$e" ] && skip=1 && break
  done
  [ "$skip" -eq 1 ] && continue
  for p in "${patterns[@]}"; do
    if grep -HInE -- "$p" "$f" 2>/dev/null; then
      found=1
    fi
  done
done <<< "$(git ls-files 'asf/*.py' 'asf/**/*.py')"

if [ "$found" -eq 1 ]; then
  echo "check_conventions: a product convention is hardcoded (see above) — move it to the" >&2
  echo "product yaml's conventions: block and read it through asf.conventions.Conventions — or," >&2
  echo "if it is the default itself, read it from asf.conventions rather than copying it" >&2
  exit 1
fi

echo "check_conventions: clean"
exit 0
